# Oracle JDBC
jdbc.driverClassName=oracle.jdbc.OracleDriver
jdbc.url=jdbc:oracle:thin:@//127.0.0.1:1521/XEPDB1
jdbc.username=scott
jdbc.password=tiger

# (DBCP / Hikari \uB4F1 \uD480\uC740 \uD504\uB85C\uC81D\uD2B8 \uC124\uC815\uC5D0 \uB9DE\uCDB0 \uC720\uC9C0)
jdbc.maxActive=10
jdbc.initialSize=5
